server:
  port: 9090
spring:
  aplication:
    name: msvc-cliente
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/microservicios
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto:create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
