server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: clientes
          uri: http://localhost:8090
          predicates:
            - Path=/api/clientes/**
        - id: cuentas
          uri: http://localhost:9090
          predicates:
            - Path=/api/cuentas/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

